sudo: false

language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
  allow_failures:
    - php: nightly

install:
  - composer self-update
  - composer install

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
#   Coverage reporting
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.composer/cache